apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  labels:
    app: {{ include "metrics-server.name" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
