apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-server.fullname" . }}-app
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "metrics-server.name" . }}-app
